[package]
name = "weaveauth"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common" }
common-macros = { path = "../common/macros" }

axum = { workspace = true }
aide = { workspace = true, features = ["axum", "axum-json", "axum-query", "axum-form", "scalar"] }
schemars = { workspace = true, features = ["chrono04", "uuid1"] }
tokio = { workspace = true, features = ["full"] }
tower-http = { workspace = true, features = ["trace"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
figment = { workspace = true, features = ["yaml", "env", "test"] }
dotenvy = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
anyhow = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true, features = ["v4", "serde"] }
chrono = { workspace = true, features = ["serde"] }
sha2 = { workspace = true }
base64 = { workspace = true }
secrecy = { workspace = true, features = ["serde"] }
rand = { workspace = true }
argon2 = { workspace = true }
bcrypt = { workspace = true }
jsonwebtoken = { workspace = true , features = ["rust_crypto"] }
openidconnect = { workspace = true, features = ["reqwest", "native-tls"] }
rsa = { workspace = true, features = ["pem"] }
email_address = { workspace = true }
native-tls = { workspace = true }
reqwest = { workspace = true, features = ["json"] }
extism = { workspace = true, features = ["wasmtime-default-features"] }
async-trait = { workspace = true }
url = { workspace = true }

[dev-dependencies]
tower = { workspace = true, features = ["util"] }
wiremock = { workspace = true }
wat = { workspace = true }
