[package]
name = "weaveauth-bff"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { path = "../common" }
common-macros = { path = "../common/macros" }
thiserror = { workspace = true }

axum = { workspace = true }
axum-reverse-proxy = "2.2"
tokio = { workspace = true, features = ["full"] }
tower-http = { workspace = true, features = ["trace"] }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
uuid = { workspace = true, features = ["v4", "serde"] }
chrono = { workspace = true, features = ["serde"] }
reqwest = { workspace = true, features = ["form", "json", "query"] }
sha2 = "0.11"
base64 = "0.23"
rand = "0.10"
url = "2"
percent-encoding = "2"
figment = { workspace = true }
dotenvy = { workspace = true }
tower_governor = "0.8"

[dev-dependencies]
tower = { workspace = true }
