#!/usr/bin/env bash
# Writes .env (git-ignored) with fresh random secrets for the local-prod stack. Never reuse these anywhere real.
set -euo pipefail
cd "$(dirname "$0")"
[ -f .env ] && { echo ".env exists; delete it to regenerate (also 'docker compose down -v', the database keeps the old secrets)"; exit 0; }
hex() { openssl rand -hex "$1"; }
umask 077
cat > .env <<ENV
# Generated by gen-secrets.sh. Hex only: the values are substituted into config files with sed (the start scripts refuse anything but A-Za-z0-9_.-).
POSTGRES_PASSWORD=$(hex 16)
KRATOS_DB_PASSWORD=$(hex 16)
HYDRA_DB_PASSWORD=$(hex 16)
# Kratos requires exactly 32 characters for the cipher secret.
KRATOS_SECRET_COOKIE=$(hex 16)
KRATOS_SECRET_CIPHER=$(hex 16)
HYDRA_SECRET_SYSTEM=$(hex 16)
HYDRA_SECRET_COOKIE=$(hex 16)
WA_HOOKS_API_KEY=$(hex 24)
WA_BFF_INTERNAL_API_KEY=$(hex 24)
WA_BFF_CLIENT_SECRET=$(hex 24)

# Set to 1 or true to issue a session right after registration (drops verified-email-first).
KRATOS_SESSION_ON_REGISTRATION=
# Set to false together with it, or hooks refuses the unverified address.
WA_REQUIRE_VERIFIED_EMAIL=

# Google sign-in: set KRATOS_CONFIG_EXTRA=/etc/kratos/oidc-google.yml (oidc-google-phone.yml to
# also read the phone number) and both values below. Redirect URI to register at Google:
#   https://login.localhost:8443/self-service/methods/oidc/callback/google
KRATOS_CONFIG_EXTRA=
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
ENV
echo "Wrote .env"
