[package]
name = "common"
version = "0.1.0"
edition = "2024"

[features]
auth = []

[dependencies]
axum = { workspace =  true }
http = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace =  true }
aide = { workspace = true, features = ["axum", "axum-json", "axum-query", "scalar"] }
scalar_api_reference = { version = "0.2" }
schemars = { workspace = true, features = ["chrono04"] }
chrono = { workspace = true, features = ["serde"] }
strum = { workspace = true, features = ["derive"] }
